import { streamText, stepCountIs } from "ai";
import { z } from "zod";
import { advise, type Advice } from "@/server/advisors/advice";
import { type ProviderEntry } from "@/server/advisors/providers";
import { buildBatchTool } from "@/server/advisors/tools";
import { ollamaJSON, ollamaStream } from "@/server/advisors/jsonFill";
import { type ChunkSink } from "@/server/advisors/sink";

/**
 * The chunk advisor — the ONLY place the teaching content is generated by a model.
 * It runs the provider ladder (Groq batch tool → Ollama per-slot JSON / text-stream),
 * streams partial results via the injected `sink`, and returns the RAW per-slot
 * proposals as `Advice`. It does NOT coerce, validate, emit, persist, or decide
 * anything — conversation does all of that. Imports only `ai` + other advisors.
 */

/** A chunk slot: chunk-LOCAL index (0..CHUNK-1), the block type, and whether it's text. */
export interface ChunkSlot {
  index: number;
  type: string;
  isText: boolean;
}

/** Prompt strings built by conversation (advisors never import the prompt module). */
export interface ChunkPrompts {
  batchSystem: string;
  batchUser: string;
  perSlot: Record<number, { jsonSystem: string; jsonUser: string; textSystem: string; textUser: string }>;
}

/** One slot's raw model proposal + plain telemetry. `data`/`text` are UNTRUSTED. */
export interface RawSlot {
  index: number;
  data?: Record<string, unknown>;
  text?: string;
  provider: string;
  model: string;
  tokens: number;
  ms: number;
  later: boolean; // filled by a non-first provider (mop-up)
  retry: boolean; // filled on a same-provider second attempt
}

/** Schema so conversation unwraps `Advice<RawSlot[]>` via `accept()` (the only unwrap). */
export const RawSlotSchema = z.object({
  index: z.number(),
  data: z.record(z.string(), z.unknown()).optional(),
  text: z.string().optional(),
  provider: z.string(),
  model: z.string(),
  tokens: z.number(),
  ms: z.number(),
  later: z.boolean(),
  retry: z.boolean(),
});
export const RawSlotArraySchema = z.array(RawSlotSchema);

const nonEmpty = (data: Record<string, unknown> | undefined, text: string | undefined) =>
  (text != null && text.trim().length > 0) || (data != null && Object.keys(data).length > 0);

export async function fillChunk(
  slots: ChunkSlot[],
  chain: ProviderEntry[],
  prompts: ChunkPrompts,
  sink: ChunkSink,
  signal: AbortSignal,
): Promise<Advice<RawSlot[]>> {
  const collected: RawSlot[] = [];
  const done = new Set<number>();
  const record = (r: RawSlot) => {
    if (done.has(r.index)) return;
    done.add(r.index);
    collected.push(r);
  };
  const start = Date.now();
  const budgetSpent = () => Date.now() - start > 90_000; // per-chunk budget (3 slots)
  const withTimeout = (ms: number) => AbortSignal.any([signal, AbortSignal.timeout(ms)]);

  for (let pi = 0; pi < chain.length; pi++) {
    if (signal.aborted || budgetSpent()) break;
    const p = chain[pi];
    const later = pi > 0;
    const remaining = slots.filter((s) => !done.has(s.index));
    if (remaining.length === 0) break;

    if (p.caps.supportsTools) {
      // TOOL PATH — one batch stream, one tool call per slot (per-slot tokens n/a).
      const batch = buildBatchTool(remaining.map((s) => ({ slot: s.index })), (slot, data, text) => {
        const t = typeof text === "string" ? text : "";
        if (!nonEmpty(data, t)) return;
        if (t) sink.onText(slot, t);
        else sink.onSlot(slot, data);
        record({ index: slot, data: t ? undefined : data, text: t || undefined, provider: p.name, model: p.name, tokens: 0, ms: 0, later, retry: false });
      });
      try {
        const res = streamText({
          model: p.model,
          system: prompts.batchSystem,
          prompt: prompts.batchUser,
          tools: batch.tools,
          toolChoice: "required",
          stopWhen: stepCountIs(remaining.length + 4),
          temperature: 0.7,
          maxRetries: 1,
          abortSignal: withTimeout(90_000),
        });
        await res.consumeStream();
      } catch (e) {
        sink.onError?.(p.name, e); // Law 11 — never swallow: surface the failed tool-call, THEN fall through
        if (signal.aborted) break;
      }
    } else if (p.ollama) {
      // JSON / TEXT-STREAM PATH — per slot, sequential (Ollama concurrency dead).
      const oll = p.ollama;
      for (const s of remaining) {
        if (signal.aborted || budgetSpent()) break;
        if (done.has(s.index)) continue;
        const pr = prompts.perSlot[s.index];
        if (!pr) continue;

        const attempt = async (retry: boolean): Promise<boolean> => {
          try {
            if (s.isText) {
              const r = await ollamaStream(oll.nativeBase, oll.modelId, pr.textSystem, pr.textUser, withTimeout(30_000), (full) => sink.onText(s.index, full));
              if (!r.text.trim()) return false;
              record({ index: s.index, text: r.text, provider: p.name, model: oll.modelId, tokens: r.tokens, ms: r.ms, later, retry });
              return true;
            }
            const r = await ollamaJSON(oll.nativeBase, oll.modelId, pr.jsonSystem, pr.jsonUser, withTimeout(30_000));
            const data = r.parsed ? r.data : { text: r.raw }; // raw text handed on for coerce (RUNG-4)
            if (!nonEmpty(data, undefined)) return false;
            sink.onSlot(s.index, data);
            record({ index: s.index, data, provider: p.name, model: oll.modelId, tokens: r.tokens, ms: r.ms, later, retry });
            return true;
          } catch (e) {
            sink.onError?.(p.name, e); // Law 11 — surface the local-model failure too, never silent
            return false;
          }
        };

        let ok = await attempt(false);
        if (!ok && !signal.aborted && !budgetSpent()) ok = await attempt(true); // same-provider retry → rung 3
      }
    }
  }

  return advise<RawSlot[]>(collected);
}
